In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
import matplotlib as plt

In [3]:
path = r"H:\Economics\Finance(Prof.Heidari-Aghajanzadeh)\Data"
n1 = path + '\Stocks_Prices_1399-07-20' + '.csv'
df1 = pd.read_csv(n1)

In [5]:
def vv(row):
    X = row.split('-')
    return X[0]+X[1]+X[2]

In [6]:
def DriveYearMonthDay(d):
    d['jalaliDate'] = d['jalaliDate'].astype(str)
    d['Year'] = d['jalaliDate'].str[0:4]
    d['Month'] = d['jalaliDate'].str[4:6]
    d['Day'] = d['jalaliDate'].str[6:8]
    d['jalaliDate'] = d['jalaliDate'].astype(int)
    return d

In [7]:
df1['jalaliDate'] = df1['jalaliDate'].apply(vv)

In [8]:
df = df1

In [9]:
symbols = [ 'سپرده','هما','وهنر-پذيره','نکالا','تکالا','اکالا','توسعه گردشگری ','وآفر','ودانا','نشار','نبورس','چبسپا','بدکو','چکارم','تراک','کباده','فبستم','تولیددارو','قیستو','خلیبل','پشاهن','قاروم','هوایی سامان','کورز','شلیا','دتهران','نگین','کایتا','غیوان','تفیرو','سپرمی','بتک']
df = df.drop(df[df['name'].isin(symbols)].index)
df = df.drop(df[df.group_name== 'صندوق سرمایه گذاری قابل معامله'].index)
df = df.drop(df[(df.name == 'اتکای')&(df.close_price == 1000)].index)
df = df.drop_duplicates()
df = df.drop(df.loc[(df['volume'] == 0)].index).sort_values(by =['name','jalaliDate']).drop(columns = ['volume','quantity'])
df = DriveYearMonthDay(df)

In [11]:
n2 = path + '\\balance sheet - 9811' + '.csv'
df2 = pd.read_csv(n2)

In [18]:
df2[['symbol', 'year','total_assets']]

          symbol  year  total_assets
0          آ س پ  1388      268410.0
1          آ س پ  1390      573994.0
2          آ س پ  1391      769359.0
3          آ س پ  1392     1192428.0
4          آ س پ  1393     1220730.0
5          آ س پ  1394     1447582.0
6          آ س پ  1395     1436962.0
7          آ س پ  1396     1448870.0
8          آ س پ  1397     1423180.0
9           آبفر  1382       60335.0
10          آبفر  1383       55115.0
11          آبفر  1384       51225.0
12          آبفر  1385       52688.0
13          آبین  1391      377226.0
14          آبین  1392      403218.0
15          آبین  1393      414260.0
16          آبین  1394      432697.0
17          آبین  1395      440408.0
18          آبین  1396      459318.0
19          آبین  1397      516865.0
20          آداک  1394     3856427.0
21          آداک  1396     4532492.0
22          آداک  1397     4617889.0
23     آرد تجارت  1384       31639.0
24         آرمان  1390      660360.0
25         آرمان  1391     1191164.0
26         آرمان  1392     2545662.0
27         آرمان  1393     4201896.0
28         آرمان  1395     4363005.0
29         آرمان  1396     5128429.0
...          ...   ...           ...
11594     گوهران  1391     4374140.0
11595     گوهران  1393     4918952.0
11596     گوهران  1395     3107415.0
11597     گوهران  1396     3568185.0
11598     گوهران  1397     3996403.0
11599      گپارس  1388       25443.0
11600      گپارس  1389       21517.0
11601      گپارس  1390       19981.0
11602      گپارس  1391       17196.0
11603      گپارس  1392       18393.0
11604      گپارس  1393       17355.0
11605      گپارس  1394       17577.0
11606      گپارس  1395       15907.0
11607      گپارس  1396       16774.0
11608      گپارس  1397       18678.0
11609      گکوثر  1393      247888.0
11610      گکوثر  1394      340839.0
11611      گکوثر  1395      438152.0
11612      گکوثر  1396      435301.0
11613      گکوثر  1397      404599.0
11614       گکیش  1387       34104.0
11615       گکیش  1389       69722.0
11616       گکیش  1390       34783.0
11617       گکیش  1391       26065.0
11618       گکیش  1392       30393.0
11619       گکیش  1393       46986.0
11620       گکیش  1394       50939.0
11621       گکیش  1395       58532.0
11622       گکیش  1396       68148.0
11623       گکیش  1397       87173.0

[11624 rows x 3 columns]